packages:
  github.com/fintechain/skeleton/internal/domain/component:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Identifiable:
      Component:
      Registry:
      System:
      Factory:
      Operation:
      Service:
  github.com/fintechain/skeleton/internal/domain/plugin:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Plugin:
      PluginManager:
  github.com/fintechain/skeleton/internal/domain/storage:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Store:
      Engine:
      StoreConfig:
      Transactional:
      Transaction:
      MultiStore:
      MultiStoreService:
      Versioned:
      RangeQueryable:
  github.com/fintechain/skeleton/internal/domain/config:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Configuration:
      ConfigurationSource:
  github.com/fintechain/skeleton/internal/domain/context:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Context:
  github.com/fintechain/skeleton/internal/domain/logging:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Logger:
      LoggerService:
  github.com/fintechain/skeleton/internal/domain/event:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      Subscription:
      EventBus:
      EventBusService:
  github.com/fintechain/skeleton/internal/domain/runtime:
    config:
      dir: "test/unit/mocks"
      filename: "Mock{{.InterfaceName}}.go"
      pkgname: "mocks"
    interfaces:
      RuntimeEnvironment:
