// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	component "github.com/fintechain/skeleton/internal/domain/component"
	context "github.com/fintechain/skeleton/internal/domain/context"

	mock "github.com/stretchr/testify/mock"
)

// MockComponent is an autogenerated mock type for the Component type
type MockComponent struct {
	mock.Mock
}

type MockComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponent) EXPECT() *MockComponent_Expecter {
	return &MockComponent_Expecter{mock: &_m.Mock}
}

// Description provides a mock function with no fields
func (_m *MockComponent) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockComponent_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockComponent_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Description() *MockComponent_Description_Call {
	return &MockComponent_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockComponent_Description_Call) Run(run func()) *MockComponent_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Description_Call) Return(_a0 string) *MockComponent_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Description_Call) RunAndReturn(run func() string) *MockComponent_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Dispose provides a mock function with no fields
func (_m *MockComponent) Dispose() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dispose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponent_Dispose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispose'
type MockComponent_Dispose_Call struct {
	*mock.Call
}

// Dispose is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Dispose() *MockComponent_Dispose_Call {
	return &MockComponent_Dispose_Call{Call: _e.mock.On("Dispose")}
}

func (_c *MockComponent_Dispose_Call) Run(run func()) *MockComponent_Dispose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Dispose_Call) Return(_a0 error) *MockComponent_Dispose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Dispose_Call) RunAndReturn(run func() error) *MockComponent_Dispose_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockComponent) ID() component.ComponentID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 component.ComponentID
	if rf, ok := ret.Get(0).(func() component.ComponentID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ComponentID)
	}

	return r0
}

// MockComponent_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockComponent_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockComponent_Expecter) ID() *MockComponent_ID_Call {
	return &MockComponent_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockComponent_ID_Call) Run(run func()) *MockComponent_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_ID_Call) Return(_a0 component.ComponentID) *MockComponent_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_ID_Call) RunAndReturn(run func() component.ComponentID) *MockComponent_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function with given fields: ctx, system
func (_m *MockComponent) Initialize(ctx context.Context, system component.System) error {
	ret := _m.Called(ctx, system)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, component.System) error); ok {
		r0 = rf(ctx, system)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponent_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockComponent_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - system component.System
func (_e *MockComponent_Expecter) Initialize(ctx interface{}, system interface{}) *MockComponent_Initialize_Call {
	return &MockComponent_Initialize_Call{Call: _e.mock.On("Initialize", ctx, system)}
}

func (_c *MockComponent_Initialize_Call) Run(run func(ctx context.Context, system component.System)) *MockComponent_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(component.System))
	})
	return _c
}

func (_c *MockComponent_Initialize_Call) Return(_a0 error) *MockComponent_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Initialize_Call) RunAndReturn(run func(context.Context, component.System) error) *MockComponent_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockComponent) Metadata() component.Metadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 component.Metadata
	if rf, ok := ret.Get(0).(func() component.Metadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(component.Metadata)
		}
	}

	return r0
}

// MockComponent_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockComponent_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Metadata() *MockComponent_Metadata_Call {
	return &MockComponent_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockComponent_Metadata_Call) Run(run func()) *MockComponent_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Metadata_Call) Return(_a0 component.Metadata) *MockComponent_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Metadata_Call) RunAndReturn(run func() component.Metadata) *MockComponent_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockComponent) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockComponent_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockComponent_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Name() *MockComponent_Name_Call {
	return &MockComponent_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockComponent_Name_Call) Run(run func()) *MockComponent_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Name_Call) Return(_a0 string) *MockComponent_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Name_Call) RunAndReturn(run func() string) *MockComponent_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockComponent) Type() component.ComponentType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 component.ComponentType
	if rf, ok := ret.Get(0).(func() component.ComponentType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ComponentType)
	}

	return r0
}

// MockComponent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockComponent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Type() *MockComponent_Type_Call {
	return &MockComponent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockComponent_Type_Call) Run(run func()) *MockComponent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Type_Call) Return(_a0 component.ComponentType) *MockComponent_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Type_Call) RunAndReturn(run func() component.ComponentType) *MockComponent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with no fields
func (_m *MockComponent) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockComponent_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockComponent_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockComponent_Expecter) Version() *MockComponent_Version_Call {
	return &MockComponent_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockComponent_Version_Call) Run(run func()) *MockComponent_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponent_Version_Call) Return(_a0 string) *MockComponent_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponent_Version_Call) RunAndReturn(run func() string) *MockComponent_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponent creates a new instance of MockComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponent {
	mock := &MockComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
