// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	component "github.com/fintechain/skeleton/internal/domain/component"
	context "github.com/fintechain/skeleton/internal/domain/context"

	mock "github.com/stretchr/testify/mock"
)

// MockLoggerService is an autogenerated mock type for the LoggerService type
type MockLoggerService struct {
	mock.Mock
}

type MockLoggerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerService) EXPECT() *MockLoggerService_Expecter {
	return &MockLoggerService_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: msg, args
func (_m *MockLoggerService) Debug(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLoggerService_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLoggerService_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLoggerService_Expecter) Debug(msg interface{}, args ...interface{}) *MockLoggerService_Debug_Call {
	return &MockLoggerService_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLoggerService_Debug_Call) Run(run func(msg string, args ...interface{})) *MockLoggerService_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerService_Debug_Call) Return() *MockLoggerService_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerService_Debug_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerService_Debug_Call {
	_c.Run(run)
	return _c
}

// Description provides a mock function with no fields
func (_m *MockLoggerService) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLoggerService_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockLoggerService_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Description() *MockLoggerService_Description_Call {
	return &MockLoggerService_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockLoggerService_Description_Call) Run(run func()) *MockLoggerService_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Description_Call) Return(_a0 string) *MockLoggerService_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Description_Call) RunAndReturn(run func() string) *MockLoggerService_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Dispose provides a mock function with no fields
func (_m *MockLoggerService) Dispose() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dispose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoggerService_Dispose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispose'
type MockLoggerService_Dispose_Call struct {
	*mock.Call
}

// Dispose is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Dispose() *MockLoggerService_Dispose_Call {
	return &MockLoggerService_Dispose_Call{Call: _e.mock.On("Dispose")}
}

func (_c *MockLoggerService_Dispose_Call) Run(run func()) *MockLoggerService_Dispose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Dispose_Call) Return(_a0 error) *MockLoggerService_Dispose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Dispose_Call) RunAndReturn(run func() error) *MockLoggerService_Dispose_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: msg, args
func (_m *MockLoggerService) Error(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLoggerService_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLoggerService_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLoggerService_Expecter) Error(msg interface{}, args ...interface{}) *MockLoggerService_Error_Call {
	return &MockLoggerService_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLoggerService_Error_Call) Run(run func(msg string, args ...interface{})) *MockLoggerService_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerService_Error_Call) Return() *MockLoggerService_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerService_Error_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerService_Error_Call {
	_c.Run(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockLoggerService) ID() component.ComponentID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 component.ComponentID
	if rf, ok := ret.Get(0).(func() component.ComponentID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ComponentID)
	}

	return r0
}

// MockLoggerService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockLoggerService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) ID() *MockLoggerService_ID_Call {
	return &MockLoggerService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockLoggerService_ID_Call) Run(run func()) *MockLoggerService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_ID_Call) Return(_a0 component.ComponentID) *MockLoggerService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_ID_Call) RunAndReturn(run func() component.ComponentID) *MockLoggerService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: msg, args
func (_m *MockLoggerService) Info(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLoggerService_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLoggerService_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLoggerService_Expecter) Info(msg interface{}, args ...interface{}) *MockLoggerService_Info_Call {
	return &MockLoggerService_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLoggerService_Info_Call) Run(run func(msg string, args ...interface{})) *MockLoggerService_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerService_Info_Call) Return() *MockLoggerService_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerService_Info_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerService_Info_Call {
	_c.Run(run)
	return _c
}

// Initialize provides a mock function with given fields: ctx, system
func (_m *MockLoggerService) Initialize(ctx context.Context, system component.System) error {
	ret := _m.Called(ctx, system)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, component.System) error); ok {
		r0 = rf(ctx, system)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoggerService_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockLoggerService_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - system component.System
func (_e *MockLoggerService_Expecter) Initialize(ctx interface{}, system interface{}) *MockLoggerService_Initialize_Call {
	return &MockLoggerService_Initialize_Call{Call: _e.mock.On("Initialize", ctx, system)}
}

func (_c *MockLoggerService_Initialize_Call) Run(run func(ctx context.Context, system component.System)) *MockLoggerService_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(component.System))
	})
	return _c
}

func (_c *MockLoggerService_Initialize_Call) Return(_a0 error) *MockLoggerService_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Initialize_Call) RunAndReturn(run func(context.Context, component.System) error) *MockLoggerService_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function with no fields
func (_m *MockLoggerService) IsRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockLoggerService_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockLoggerService_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) IsRunning() *MockLoggerService_IsRunning_Call {
	return &MockLoggerService_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockLoggerService_IsRunning_Call) Run(run func()) *MockLoggerService_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_IsRunning_Call) Return(_a0 bool) *MockLoggerService_IsRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_IsRunning_Call) RunAndReturn(run func() bool) *MockLoggerService_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockLoggerService) Metadata() component.Metadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 component.Metadata
	if rf, ok := ret.Get(0).(func() component.Metadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(component.Metadata)
		}
	}

	return r0
}

// MockLoggerService_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockLoggerService_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Metadata() *MockLoggerService_Metadata_Call {
	return &MockLoggerService_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockLoggerService_Metadata_Call) Run(run func()) *MockLoggerService_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Metadata_Call) Return(_a0 component.Metadata) *MockLoggerService_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Metadata_Call) RunAndReturn(run func() component.Metadata) *MockLoggerService_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockLoggerService) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLoggerService_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockLoggerService_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Name() *MockLoggerService_Name_Call {
	return &MockLoggerService_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockLoggerService_Name_Call) Run(run func()) *MockLoggerService_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Name_Call) Return(_a0 string) *MockLoggerService_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Name_Call) RunAndReturn(run func() string) *MockLoggerService_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockLoggerService) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoggerService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockLoggerService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoggerService_Expecter) Start(ctx interface{}) *MockLoggerService_Start_Call {
	return &MockLoggerService_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockLoggerService_Start_Call) Run(run func(ctx context.Context)) *MockLoggerService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLoggerService_Start_Call) Return(_a0 error) *MockLoggerService_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Start_Call) RunAndReturn(run func(context.Context) error) *MockLoggerService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with no fields
func (_m *MockLoggerService) Status() component.ServiceStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 component.ServiceStatus
	if rf, ok := ret.Get(0).(func() component.ServiceStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ServiceStatus)
	}

	return r0
}

// MockLoggerService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockLoggerService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Status() *MockLoggerService_Status_Call {
	return &MockLoggerService_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockLoggerService_Status_Call) Run(run func()) *MockLoggerService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Status_Call) Return(_a0 component.ServiceStatus) *MockLoggerService_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Status_Call) RunAndReturn(run func() component.ServiceStatus) *MockLoggerService_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *MockLoggerService) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoggerService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockLoggerService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoggerService_Expecter) Stop(ctx interface{}) *MockLoggerService_Stop_Call {
	return &MockLoggerService_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockLoggerService_Stop_Call) Run(run func(ctx context.Context)) *MockLoggerService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLoggerService_Stop_Call) Return(_a0 error) *MockLoggerService_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Stop_Call) RunAndReturn(run func(context.Context) error) *MockLoggerService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockLoggerService) Type() component.ComponentType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 component.ComponentType
	if rf, ok := ret.Get(0).(func() component.ComponentType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ComponentType)
	}

	return r0
}

// MockLoggerService_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockLoggerService_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Type() *MockLoggerService_Type_Call {
	return &MockLoggerService_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockLoggerService_Type_Call) Run(run func()) *MockLoggerService_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Type_Call) Return(_a0 component.ComponentType) *MockLoggerService_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Type_Call) RunAndReturn(run func() component.ComponentType) *MockLoggerService_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with no fields
func (_m *MockLoggerService) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLoggerService_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockLoggerService_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockLoggerService_Expecter) Version() *MockLoggerService_Version_Call {
	return &MockLoggerService_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockLoggerService_Version_Call) Run(run func()) *MockLoggerService_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerService_Version_Call) Return(_a0 string) *MockLoggerService_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggerService_Version_Call) RunAndReturn(run func() string) *MockLoggerService_Version_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function with given fields: msg, args
func (_m *MockLoggerService) Warn(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLoggerService_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLoggerService_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *MockLoggerService_Expecter) Warn(msg interface{}, args ...interface{}) *MockLoggerService_Warn_Call {
	return &MockLoggerService_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLoggerService_Warn_Call) Run(run func(msg string, args ...interface{})) *MockLoggerService_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLoggerService_Warn_Call) Return() *MockLoggerService_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoggerService_Warn_Call) RunAndReturn(run func(string, ...interface{})) *MockLoggerService_Warn_Call {
	_c.Run(run)
	return _c
}

// NewMockLoggerService creates a new instance of MockLoggerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerService {
	mock := &MockLoggerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
