// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	component "github.com/fintechain/skeleton/internal/domain/component"
	context "github.com/fintechain/skeleton/internal/domain/context"

	mock "github.com/stretchr/testify/mock"
)

// MockOperation is an autogenerated mock type for the Operation type
type MockOperation struct {
	mock.Mock
}

type MockOperation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperation) EXPECT() *MockOperation_Expecter {
	return &MockOperation_Expecter{mock: &_m.Mock}
}

// Description provides a mock function with no fields
func (_m *MockOperation) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOperation_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockOperation_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockOperation_Expecter) Description() *MockOperation_Description_Call {
	return &MockOperation_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockOperation_Description_Call) Run(run func()) *MockOperation_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_Description_Call) Return(_a0 string) *MockOperation_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Description_Call) RunAndReturn(run func() string) *MockOperation_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Dispose provides a mock function with no fields
func (_m *MockOperation) Dispose() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dispose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOperation_Dispose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispose'
type MockOperation_Dispose_Call struct {
	*mock.Call
}

// Dispose is a helper method to define mock.On call
func (_e *MockOperation_Expecter) Dispose() *MockOperation_Dispose_Call {
	return &MockOperation_Dispose_Call{Call: _e.mock.On("Dispose")}
}

func (_c *MockOperation_Dispose_Call) Run(run func()) *MockOperation_Dispose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_Dispose_Call) Return(_a0 error) *MockOperation_Dispose_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Dispose_Call) RunAndReturn(run func() error) *MockOperation_Dispose_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockOperation) Execute(ctx context.Context, input component.Input) (component.Output, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 component.Output
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, component.Input) (component.Output, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, component.Input) component.Output); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(component.Output)
	}

	if rf, ok := ret.Get(1).(func(context.Context, component.Input) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperation_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOperation_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input component.Input
func (_e *MockOperation_Expecter) Execute(ctx interface{}, input interface{}) *MockOperation_Execute_Call {
	return &MockOperation_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockOperation_Execute_Call) Run(run func(ctx context.Context, input component.Input)) *MockOperation_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(component.Input))
	})
	return _c
}

func (_c *MockOperation_Execute_Call) Return(_a0 component.Output, _a1 error) *MockOperation_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperation_Execute_Call) RunAndReturn(run func(context.Context, component.Input) (component.Output, error)) *MockOperation_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockOperation) ID() component.ComponentID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 component.ComponentID
	if rf, ok := ret.Get(0).(func() component.ComponentID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ComponentID)
	}

	return r0
}

// MockOperation_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockOperation_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockOperation_Expecter) ID() *MockOperation_ID_Call {
	return &MockOperation_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockOperation_ID_Call) Run(run func()) *MockOperation_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_ID_Call) Return(_a0 component.ComponentID) *MockOperation_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_ID_Call) RunAndReturn(run func() component.ComponentID) *MockOperation_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function with given fields: ctx, system
func (_m *MockOperation) Initialize(ctx context.Context, system component.System) error {
	ret := _m.Called(ctx, system)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, component.System) error); ok {
		r0 = rf(ctx, system)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOperation_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockOperation_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - system component.System
func (_e *MockOperation_Expecter) Initialize(ctx interface{}, system interface{}) *MockOperation_Initialize_Call {
	return &MockOperation_Initialize_Call{Call: _e.mock.On("Initialize", ctx, system)}
}

func (_c *MockOperation_Initialize_Call) Run(run func(ctx context.Context, system component.System)) *MockOperation_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(component.System))
	})
	return _c
}

func (_c *MockOperation_Initialize_Call) Return(_a0 error) *MockOperation_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Initialize_Call) RunAndReturn(run func(context.Context, component.System) error) *MockOperation_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockOperation) Metadata() component.Metadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 component.Metadata
	if rf, ok := ret.Get(0).(func() component.Metadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(component.Metadata)
		}
	}

	return r0
}

// MockOperation_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockOperation_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockOperation_Expecter) Metadata() *MockOperation_Metadata_Call {
	return &MockOperation_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockOperation_Metadata_Call) Run(run func()) *MockOperation_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_Metadata_Call) Return(_a0 component.Metadata) *MockOperation_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Metadata_Call) RunAndReturn(run func() component.Metadata) *MockOperation_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockOperation) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOperation_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOperation_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOperation_Expecter) Name() *MockOperation_Name_Call {
	return &MockOperation_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOperation_Name_Call) Run(run func()) *MockOperation_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_Name_Call) Return(_a0 string) *MockOperation_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Name_Call) RunAndReturn(run func() string) *MockOperation_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockOperation) Type() component.ComponentType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 component.ComponentType
	if rf, ok := ret.Get(0).(func() component.ComponentType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(component.ComponentType)
	}

	return r0
}

// MockOperation_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockOperation_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockOperation_Expecter) Type() *MockOperation_Type_Call {
	return &MockOperation_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockOperation_Type_Call) Run(run func()) *MockOperation_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_Type_Call) Return(_a0 component.ComponentType) *MockOperation_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Type_Call) RunAndReturn(run func() component.ComponentType) *MockOperation_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with no fields
func (_m *MockOperation) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOperation_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockOperation_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockOperation_Expecter) Version() *MockOperation_Version_Call {
	return &MockOperation_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockOperation_Version_Call) Run(run func()) *MockOperation_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperation_Version_Call) Return(_a0 string) *MockOperation_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOperation_Version_Call) RunAndReturn(run func() string) *MockOperation_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOperation creates a new instance of MockOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperation {
	mock := &MockOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
